name: "Build wheels and change version"
on:
  push:
    branches:
      - dev/**

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.theversion.outputs.DHLIBS_VERSION }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Poetry
        run: |
          pip install --upgrade pip
          pip install poetry build

      - name: Install dependencies
        run: poetry install

      - name: Build artifacts
        run: python -m build

      - name: Get version
        id: theversion  # Set step ID
        run: |
          DHLIBS_VERSION="$(poetry version -s)+g$(git rev-parse --short HEAD)"
          echo "Version is $DHLIBS_VERSION"
          echo "DHLIBS_VERSION=$DHLIBS_VERSION" >> $GITHUB_ENV
          echo "DHLIBS_VERSION=$DHLIBS_VERSION" >> $GITHUB_OUTPUT  # Correct output key

      - name: Upload all artifacts
        uses: actions/upload-artifact@v4.5.0
        with:
          name: dhlibs-${{ env.DHLIBS_VERSION }}-dist  # Correct artifact name
          path: dist/*

  release-dev:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Get info
        run: echo "Version is ${{ needs.build.outputs.version }}"

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download built files
        uses: actions/download-artifact@v4
        with:
          name: dhlibs-${{ needs.build.outputs.version }}-dist  # Ensure matching name

      - name: test
        run: ls

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.build.outputs.version }}
          files: "dhlibs-*-dist*"
