name: "test and linting"
on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"
jobs:
  tox:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.9", "3.10", "3.11"]
    steps:
      - name: check code
        uses: actions/checkout@v4

      - name: setup python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: install Poetry
        run: |
          pip install --user pipx
          pipx install poetry

      - name: Install dependencies
        run: |
          poetry install

      - name: run Tox
        run: poetry run tox
  pyright:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.9", "3.10", "3.11"]
    steps:
      - name: check code
        uses: actions/checkout@v4
      - name: setup python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: install Poetry
        run: |
          pip install --user pipx
          pipx install poetry

      - name: Install dependencies
        run: |
          poetry install
      - name: run pyright
        uses: jakebailey/pyright-action@v2.3.2
